source 'git@github.com:yjbGitHub/uni_podspec.git'
target 'objectRun_Example' do
    use_frameworks!
#  pod 'objectRun', :path => '../'
    pod 'objectRun'

  target 'objectRun_Tests' do
    inherit! :search_paths

    
  end
end
